include: package:lints/recommended.yaml

# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    # Treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # Treat missing returns as a warning (not a hint)
    missing_return: warning
    # Allow having TODOs in the code
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Error rules
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - empty_constructor_bodies
    - no_duplicate_case_values
    - null_check_on_nullable_type_parameter
    - prefer_void_to_null
    - unrelated_type_equality_checks
    - valid_regexps
    
    # Style rules
    - camel_case_types
    - camel_case_extensions
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - constant_identifier_names
    - directives_ordering
    - lines_longer_than_80_chars: false  # Relaxed for a hobby project
    - curly_braces_in_flow_control_structures
    
    # Good practices
    - public_member_api_docs
    - await_only_futures
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - close_sinks
    - package_api_docs: false  # Relaxed for a hobby project
    - prefer_final_fields
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures